services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    networks:
      - kafka-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    networks:
      - kafka-network
    depends_on:
      - zookeeper
    container_name: kafka1

  kafka2:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
    networks:
      - kafka-network
    depends_on:
      - zookeeper
    container_name: kafka2

  kafka3:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
    networks:
      - kafka-network
    depends_on:
      - zookeeper
    container_name: kafka3

  scala-play-corporate-equipment-allocation:
    image: scala-play-corporate-equipment-allocation:latest
    environment:
      KAFKA_BROKER_HOST: 'kafka1:9092,kafka2:9093,kafka3:9094'
      JWT_SECRET_KEY: 
      JWT_ISSUER: 

      DB_HOST: "jdbc:mysql://localhost:3306/project_scala"
      DB_PORT: 3306
      DB_USER: "root"
      DB_PASSWORD: "Root@123"
      DB_NAME: 
    ports:
      - "9000:9000"

    networks:
      - kafka-network
    container_name: reservation-service-app
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - zookeeper

  notification-service:
    image: notification-service:latest
    environment:
      KAFKA_BROKER_HOST: 'kafka1:9092,kafka2:9093,kafka3:9094'
      SENDER_MAIL: 
      SENDER_MAIL_PASSWORD: 

    networks:
      - kafka-network
    container_name: notification-service-app
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - zookeeper

networks:
  kafka-network:
    driver: bridge
